<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-M2IH1P5" name="com.jbk.utilities.DataProviderWithExcel" tests="1" failures="0" timestamp="25 Sep 2020 13:45:06 GMT" time="0.000" errors="1">
  <testcase name="test01" time="0.000" classname="com.jbk.utilities.DataProviderWithExcel">
    <error type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] com.jbk.utilities.DataProviderWithExcel.getData(java.lang.String,java.lang.String) throws java.lang.Exception parameters unresolved:  at 0 type class java.lang.String
 at 1 type class java.lang.String
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] com.jbk.utilities.DataProviderWithExcel.getData(java.lang.String,java.lang.String) throws java.lang.Exception parameters unresolved:  at 0 type class java.lang.String
 at 1 type class java.lang.String

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:156)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:106)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:436)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1253)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- test01 -->
</testsuite> <!-- com.jbk.utilities.DataProviderWithExcel -->
